name: SuperItem
main: cf.wayzer.SuperItem.Main
version: @version@
author: Way__Zer
description: description!
commands: 
  SuperItem:
    description: SuperItem Main Command
    usage: /SuperItem help
    aliases: ["si"]